# -*- coding: utf-8 -*-
"""CodePlotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhBfHfV6Uf4iWU9niB4WGwYt8EQWG7VB

# **Instalando o Plotly**
"""

pip install plotly

"""# **Estrutura de dados**"""

import plotly.express as px


# Criando a instância da Figura
fig = px.line(x=[1,2, 3], y=[1, 2, 3])

# imprimindo a instância da figura
print(fig)

"""# **Tipos de Gráficos na Plotly**

### **Gráficos de dispersão (Scatter Plots)**
"""

import plotly.express as px

# usando o conjunto de dados da íris
df = px.data.iris()

# traçando o gráfico de dispersão
fig = px.scatter(df, x="species", y="petal_width",
                 title='Exemplo de Gráfico de Dispersão com Plotly')

# mostrando o gráfico
fig.show()

"""### **Gráficos de linha (Line  Charts)**




"""

import pandas as pd
import plotly.express as px

# Criando um DataFrame com Pandas
dados = {'dias': ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Dom'],
         'ligacoes': [68, 53, 50, 41, 70, 12, 5]}
df = pd.DataFrame(dados)

# Criando o gráfico de linha
fig = px.line(df, x='dias', y='ligacoes', title='Ligações da Semana' )

# Mudando o nome de exibição dos eixos X e Y
fig.update_layout(
    xaxis_title='Dias da semana',
    yaxis_title='Quantidade de ligações')

# Exibindo o gráfico
fig.show()

"""


### **Gráficos de barras (Bar  Charts)**



"""

import plotly.express as px

# Dados de exemplo
categorias = ['A', 'B', 'C', 'D', 'E']
valores = [4, 7, 1, 3, 9]

# Criando o gráfico de barras
fig = px.bar(x=categorias, y=valores, labels={'x':'Categorias', 'y':'Valores'},
             title='Exemplo de Gráfico de Barras com Plotly')

# Exibindo o gráfico
fig.show()

"""### **Gráficos de barras (Bar  Charts)**

"""

import pandas as pd
import plotly.express as px

# Criando um DataFrame com P
dados = {'Categoria': ['Vermelho', 'Verde', 'Roxo', 'Azul'],
         'Contagem': [656, 789, 300, 946]}
df = pd.DataFrame(dados)

# Criando o gráfico de pizza
fig = px.pie(df, values='Contagem', names='Categoria', title='Exemplo de gráfico de Pizza')

# Exibindo o gráfico
fig.show()

"""### **Mapas de calor (Heatmaps)**

"""

import pandas as pd
import plotly.express as px
import numpy as np

# Criando um DataFrame com valores aleatórios utilizando Pandas e numpy
dados = pd.DataFrame({
    'Variavel1': np.random.randn(10),
    'Variavel2': np.random.randn(10),
})

# Criando o mapa de calor
fig = px.density_heatmap(dados,
                         x='Variavel1',
                         y='Variavel2',
                         title='Exemplo de Mapa de Calor')

# Exibindo o gráfico
fig.show()

"""### **Mapas de calor (Heatmaps)**"""

import pandas as pd
import plotly.graph_objects as go
import numpy as np

# Criando os dados.
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
x, y = np.meshgrid(x, y)
z = np.random.randn(100, 100)  # Valores sendo gerados de forma aleatória

df = pd.DataFrame({
    'X': x.flatten(),
    'Y': y.flatten(),
    'Z': z.flatten()
})

# Criando o gráfico
fig = go.Figure(data=[go.Surface(x=df['X'].values.reshape(100, 100),
                                 y=df['Y'].values.reshape(100, 100),
                                 z=df['Z'].values.reshape(100, 100))])

# Atualizando o layout
fig.update_layout(scene=dict(
                    xaxis_title='Eixo X',
                    yaxis_title='Eixo Y',
                    zaxis_title='Eixo Z'),
                    title='Gráfico de Superfície 3D')

# Exibindo o gráfico
fig.show()

"""### **Gráficos de Caixa (Box Plots)**"""

import plotly.tools as tls
import plotly.graph_objects as go

# Dados de exemplo
dados1 = [1, 2, 2, 3, 3, 3, 4, 4, 5]
dados2 = [2, 3, 3, 4, 4, 5, 5, 6, 6]

# Criar os traces (caixas) para os dados
trace1 = go.Box(y=dados1, name='Dados 1', boxpoints='all', jitter=0.3, pointpos=-1.8)
trace2 = go.Box(y=dados2, name='Dados 2', boxpoints='all', jitter=0.3, pointpos=-1.8)

# Layout do gráfico
layout = go.Layout(title='Gráfico de Caixa (Box Plot)',
                   yaxis=dict(title='Valores'),
                   boxmode='group')

# Criar a figura
fig = go.Figure(data=[trace1, trace2], layout=layout)

# Exibir o gráfico
fig.show()

"""# **Casos de Uso**"""

"""### **Análise Exploratória de Dados**"""

import plotly.express as px
import pandas as pd

# Gerar dados fictícios para exemplo
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [2, 3, 4, 5, 6],
    'C': ['X', 'Y', 'X', 'Y', 'Z']
})

# Gráfico de dispersão interativo
fig = px.scatter(df, x='A', y='B', color='C', size='B', hover_data=['A'])

# Exibir o gráfico
fig.show()

"""### **Visualização de Tendências ao Longo do Tempo**"""

import plotly.express as px
import pandas as pd

# Gerar dados fictícios para exemplo
df = pd.DataFrame({
    'Data': pd.date_range(start='2022-01-01', periods=12, freq='M'),
    'Vendas': [10, 15, 8, 12, 20, 25, 18, 22, 27, 30, 35, 28]
})

# Gráfico de linhas interativo
fig = px.line(df, x='Data', y='Vendas', markers=True, title='Tendência de Vendas ao Longo do Tempo')

# Exibir o gráfico
fig.show()

"""### **Comparação de Categorias**"""

import plotly.express as px
import pandas as pd

# Gerar dados fictícios para exemplo
df = pd.DataFrame({
    'Produto': ['A', 'B', 'C', 'D'],
    'Receita': [100, 150, 120, 200]
})

# Gráfico de barras interativo
fig = px.bar(df, x='Produto', y='Receita', text='Receita', title='Comparação de Receita por Produto')

# Exibir o gráfico
fig.show()

"""### **Análise Geoespacial**"""

import plotly.express as px
import pandas as pd

# Gerar dados fictícios para exemplo
df = pd.DataFrame({
    'Cidade': ['A', 'B', 'C', 'D'],
    'Ocorrencias': [10, 5, 15, 8]
})

# Mapa de calor interativo
fig = px.density_mapbox(df, lat=[1, 2, 3, 4], lon=[1, 2, 3, 4], z='Ocorrencias',
                        radius=10, center=dict(lat=2.5, lon=2.5), zoom=1,
                        mapbox_style="stamen-terrain")

# Exibir o gráfico
fig.show()